name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Package Changelog Action"
        continue-on-error: true
        uses: cssnr/package-changelog-action@latest
