export default {
  published: [
    'cssnr/actionlint-action',
    'cssnr/actions-up-action',
    'cssnr/algolia-crawler-action',
    'cssnr/check-build-action',
    'cssnr/cloudflare-purge-cache-action',
    'cssnr/create-pull-action',
    'cssnr/docker-context-action',
    'cssnr/docker-tags-action',
    'cssnr/get-commit-action',
    'cssnr/homebrew-action',
    'cssnr/json-key-value-check-action',
    'cssnr/label-creator-action',
    'cssnr/mirror-repository-action',
    'cssnr/mozilla-addon-update-action',
    'cssnr/npm-outdated-action',
    'cssnr/package-changelog-action',
    'cssnr/parse-issue-form-action',
    'cssnr/portainer-stack-deploy-action',
    'cssnr/stack-deploy-action',
    'cssnr/toml-action',
    'cssnr/update-json-value-action',
    'cssnr/update-version-tags-action',
    'cssnr/upload-release-action',
    'cssnr/virustotal-action',
    'cssnr/web-request-action',
    'cssnr/zensical-action',
  ],
  unpublished: [
    'cssnr/create-files-action',
    'cssnr/draft-release-action',
    'cssnr/env-json-action',
    'cssnr/push-artifacts-action',
    'cssnr/validate-outputs-action',
    'smashedr/update-release-notes-action',
    'smashedr/combine-release-notes-action',
  ],
  template: [
    'smashedr/js-test-action',
    'smashedr/py-test-action',
    'smashedr/ts-test-action',
    'smashedr/docker-test-action',
    'smashedr/test-action-uv',
    'smashedr/test-action-py',
  ],
}
